### ISSUE TITLE
integration with opsweekly

### ISSUE THREAD

**Issue by jeanfrancis** [ustream/openduty#27]
Has any one tried integration with Opsweekly ?

**Comment by deathowl** [comment]
it won't work yet, but i will make it work. Expect it in  a week.

**Comment by deathowl** [comment]
This was a bit "forgotten". I'm starting the work needed on the weekend. I already did the research, so it can be easily done.

**Comment by deathowl** [comment]
The Etsy guys merged the support for Openduty too. https://github.com/etsy/opsweekly/pull/56 Closing this one.
