### ISSUE TITLE
consul integration

### ISSUE THREAD

**Issue by pepov** [ustream/openduty#29]
The current integration method is to use the public api to notify openduty from an external source like nagios. I'm thinking about the reverse for an external source like consul. If openduty would have access to a local consul agent, it could register a watch for a consul service. The watch events would then be posted into a consul specific openduty api entry point. It will miss however soft/hard state and flapping detection but even it would be nice without them for a first shot.

**Comment by deathowl** [comment]
This is generally a good idea, I'd be really happy to see consul check integration.

**Comment by deathowl** [comment]
@pepov Any update on this ? Or shall i do this? If so, please let me know.

**Comment by pepov** [comment]
No, we decided to stuck with Nagios in the middle for now, but thanks for asking!
