### ISSUE TITLE
Use smarter twilio call notifications

### ISSUE THREAD

**Issue by deathowl** [ustream/openduty#37]
It should read notification message. Because it's basically able to do so.

**Comment by deathowl** [comment]
commits:
05fe5242b75ae5df68ec3a11598a4ea470b27ead and dc7a950b2d4457b5bcd463547e89b39cf53ee106 solve this.

**Comment by krutaw** [comment]
@deathowl Can you please provide an example of what your twiml output looks like to enable the smarter call notifications and call handling?
