### ISSUE TITLE
Both Demo Site and Fresh Install appears to not contain the root user

### ISSUE THREAD

**Issue by stauffec** [ustream/openduty#39]
I tried out the demo and I couldn't log in. I then cloned the repo and set it up locally. Everyone succeeded however attempting to login fails in the same way as the demo site. What can I do to troubleshoot this?

**Comment by deathowl** [comment]
As we migrated from south to djangos own migration mechanism, it seems it broke.
Create your superuser with the following command please.
 ./manage.py createsuperuser
