### ISSUE TITLE
Demo Login does not work

### ISSUE THREAD

**Issue by shakalandy** [ustream/openduty#40]
the demo at openduty.herokuapp.com seems broken to me. Login with root/toor does not work anymore.

**Comment by Cad** [comment]
Bump!

**Comment by SamPlacette** [comment]
Bump. Would love to try this out to see if it does what I want.

**Comment by deathowl** [comment]
I've been pretty busy lately, sorry. Will handle the issue tonight.

**Comment by SamPlacette** [comment]
I totally understand. I appreciate the work you do as an OSS project maintainer. :)

**Comment by deathowl** [comment]
Demo login restored. You can log in with root/toor on Heroku

**Comment by deathowl** [comment]
Please note, that the heroku instance runs with limited functionality (No notifications get delivered, it's just to demo the web interface)

**Comment by deathowl** [comment]
If you are into docker. i recommend this :  https://github.com/endticket/docker-openduty You just have to add your settings to the container, and you are good to go.
