### ISSUE TITLE
missing phonenumbers

### ISSUE THREAD

**Issue by mose** [ustream/openduty#44]
heya. After my install manage.py complained about `ImportError: No module named phonenumbers`. I suspect it may be missing in `requirements.txt`.

**Comment by deathowl** [comment]
I'll check it right away.

**Comment by deathowl** [comment]
fixed it, pull request coming in in minutes. Thanks for your patience

**Comment by deathowl** [comment]
merged, pull and test again please, you shouldnt encounter any problems anymore with this, please close the issue if fixed for you as well.

**Comment by deathowl** [comment]
Closing as you confirmed it on gitter
