### ISSUE TITLE
default login not working.

### ISSUE THREAD

**Issue by ashoksethuraman** [ustream/openduty#45]
I installed opeduty application and  database migrate everything. its running perfectly but default login username and password not working. so please help me. how to solve the issue?

Thanks,
ashok

**Comment by deathowl** [comment]
i'll check it out.

**Comment by deathowl** [comment]
until then please use the manage.py createsuperuser command

**Comment by karthicktkm** [comment]
@deathowl  Hi!
Already fixed this issue. And Thanks

**Comment by ashoksethuraman** [comment]
i create superuser its working fine now. thanks @deathowl.
