### ISSUE TITLE
Open Duty HA

### ISSUE THREAD

**Issue by sofixa** [ustream/openduty#50]
Hello.

Has anyone ever used OpenDuty in a HA, master-master mode?

Thanks

**Comment by deathowl** [comment]
Hey! I think nobody but it shouldnt be a problem, just use the same DB connection for all the django instances and use any kind of load balancing you like

**Comment by deathowl** [comment]
http://reinout.vanrees.org/weblog/2016/06/22/high-availability-django-cheap.html @sofixa does this answer your question? If yes, or no longer intereted please close the issue. Thanks.

**Comment by sofixa** [comment]
Yep, you can close, thanks :)
