### ISSUE TITLE
What does the "Repeat" field stand for ?

### ISSUE THREAD

**Issue by valouille** [ustream/openduty#51]
Hello,

I can't figure out the goal of the field "Repeat" in an "escalation-policy". Can you explain what sould I expect when I set this value ?

Thank you !

**Comment by pataquets** [comment]
Same here.

**Comment by deathowl** [comment]
Go over the list given in the escalation policy x times before giving up on notifiing people about the given incident.

**Comment by AlexanderPavlenko** [comment]
Is it actually working?
I cannot find any loop on it: https://github.com/ustream/openduty/search?q=repeat_times
