### ISSUE TITLE
Demo app is not working

### ISSUE THREAD

**Issue by tivvit** [ustream/openduty#52]
Readme says: `http://openduty.herokuapp.com , log in with root/toor`
But those credentials are not working.

**Comment by hernandesbsousa** [comment]
+1

I also just had the same problem

**Comment by tkrause** [comment]
Me three

**Comment by tickylum** [comment]
Me 4, no solutions yet?!

**Comment by hernandesbsousa** [comment]
Is there any way we can help getting this back up?

**Comment by abraden-about** [comment]
I was going to demo OpenDuty but based on what I see here I will not waste my time.

**Comment by mbielski** [comment]
Pretty bad when you get a nice article written about a project and can't see the demo because it isn't working. I've been wanting to show this to co-workers for weeks now and feel I can't because the demo is not working. WTH?

**Comment by jeremybz** [comment]
Bump

**Comment by pataquets** [comment]
Still no demo :(

**Comment by dariushazimi** [comment]
still no demo?
What's peopleeeeeeee!??

**Comment by arunpyasi** [comment]
It looks like people here are sleeping well. :P

**Comment by deathowl** [comment]
Fixing it now. Thanks for the patience, have been occupied a lot lately.

**Comment by deathowl** [comment]
Fixed. Closing
