### ISSUE TITLE
Requirements file needs to be updated

### ISSUE THREAD

**Issue by krutaw** [ustream/openduty#55]
The "kombu" entry needs to be more specific and define an actual version, otherwise an older version will be installed and thus the OrderedDict version won't be loadable by the manage.py script.  Here's the specific update that I had to make in order to get the manage.py syncdb command to work properly:

kombu==3.0.37

**Comment by krutaw** [comment]
Submitted https://github.com/ustream/openduty/pull/58 to handle this fix.

**Comment by MrWeeble** [comment]
I opened a PR #57 that fixes this (made it to include any 3.0.x kombu)

**Comment by deathowl** [comment]
Merged #57. Closing.
