### ISSUE TITLE
Django Compatibility Errors

### ISSUE THREAD

**Issue by SDasman** [ustream/openduty#95]
So I just ran the command: `pip install -r requirements.txt` in the virual env and I ran into the following errors:

`django-twilio 0.9.0 has requirement twilio<7,>=6.3.0, but you'll have twilio 4.4.0 which is incompatible.
oauth2client 1.4.11 has requirement rsa==3.1.4, but you'll have rsa 3.4.2 which is incompatible.
django-scheduler 0.7.5 has requirement argparse==1.1, but you'll have argparse 1.4.0 which is incompatible.
django-phonenumber-field 2.0.0 has requirement Django>=1.11, but you'll have django 1.8.11 which is incompatible.`

**Comment by syntaxerror13** [comment]
Hi, please note this project is not active: https://github.com/ustream/openduty/issues/92#issuecomment-374231734

**Comment by SDasman** [comment]
I was able to get everything to work. https://github.com/SDasman/openduty
Changed the whole requirements.txt file.
