### ISSUE TITLE
openduty requires Twilio of version >=0af4776a961a5b0fef8052082fb1f4027cff172e

### ISSUE THREAD

**Issue by truekonrads** [ustream/openduty#99]
Hi,

openduty won't run if twilio plugin is not at least greater than 0af4776a961a5b0fef8052082fb1f4027cff172e  commit of tiwlio.

**Comment by sysrex** [comment]
Openduty is being revived and upgrade here - https://github.com/openduty/openduty

**Comment by truekonrads** [comment]
Shall I re-open the issue there?

**Comment by sysrex** [comment]
yes please
